categories = {
    "Lager": [
        "Euro Pale Lager",
        "German Pilsener",
        "Munich Helles Lager",
        "Czech Pilsener",
        "Vienna Lager",
        "Light Lager",
        "Munich Dunkel Lager",
        "Schwarzbier",
        "Euro Dark Lager",
        "Märzen / Oktoberfest",
        "Doppelbock",
        "Eisbock",
        "Maibock / Helles Bock",
        "Baltic Porter",
        "Euro Strong Lager",
    ],
    "Ale": [
        "English Pale Ale",
        "American Pale Ale (APA)",
        "English Bitter",
        "Extra Special / Strong Bitter (ESB)",
        "Belgian Pale Ale",
        "Irish Red Ale",
        "American Amber / Red Ale",
        "Scottish Ale",
        "English Brown Ale",
        "American Brown Ale",
        "Old Ale",
        "English Strong Ale",
        "American Strong Ale",
        "Scotch Ale / Wee Heavy",
        "English Barleywine",
        "American Barleywine",
        "Belgian Dark Ale",
        "Belgian Strong Dark Ale",
        "Quadrupel (Quad)",
        "Dubbel",
        "Tripel",
    ],
    "IPA": [
        "English India Pale Ale (IPA)",
        "American IPA",
        "American Double / Imperial IPA",
        "Belgian IPA",
    ],
    "Stout": [
        "Irish Dry Stout",
        "Milk / Sweet Stout",
        "Oatmeal Stout",
        "Foreign / Export Stout",
        "Russian Imperial Stout",
        "American Stout",
        "English Stout",
    ],
    "Porter": ["English Porter", "American Porter", "Baltic Porter"],
    "Wheat Beer": [
        "Hefeweizen",
        "Kristalweizen",
        "Dunkelweizen",
        "Weizenbock",
        "Witbier",
        "Berliner Weissbier",
        "Gose",
        "Roggenbier",
    ],
    "Belgian Styles": [
        "Saison / Farmhouse Ale",
        "Bière de Garde",
        "Lambic - Fruit",
        "Lambic - Unblended",
        "Gueuze",
        "Faro",
    ],
    "Specialty": [
        "Smoked Beer",
        "Herbed / Spiced Beer",
        "Pumpkin Ale",
        "Chile Beer",
        "Scottish Gruit / Ancient Herbed Ale",
        "American Wild Ale",
        "Bière de Champagne / Bière Brut",
        "Wheatwine",
        "Sahti",
        "Kvass",
        "Braggot",
    ],
    "Hybrid": ["Kölsch", "Altbier", "California Common / Steam Beer", "Cream Ale"],
    "Light/Low Alcohol": [
        "Low Alcohol Beer",
        "American Adjunct Lager",
        "American Pale Lager",
        "Japanese Rice Lager",
        "Happoshu",
    ],
}

print(list(categories.keys()))
